# Generated by Django 4.2.18 on 2025-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Enter the prompt text')),
                ('articles', models.JSONField(default=list, help_text='List of article URLs')),
                ('videos', models.JSONField(default=list, help_text='List of video URLs')),
            ],
        ),
    ]
